kind = "mobile"
previewPath = "/"
title = "Mineral"
version = "1.0.0"
id = "artifacts/mineral"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22771

[services.development]
run = "pnpm --filter @workspace/mineral run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mineral", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mineral", "run", "serve" ]

[services.env]
PORT = "22771"
BASE_PATH = "/"
